---
title: "P8105_hw3_my2838"
output: github_document
---

```{r}
library(tidyverse)
library(ggplot2)
library(dplyr)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```
# Problem 1

```{r}
homicide = 
  read_csv("homicide-data.csv") |>
  mutate(city_state = paste(city, state, sep = ","))

homicide_city = 
  homicide |>
  group_by(city_state, disposition) |>
  count(disposition) |>
  pivot_wider(
    names_from = disposition,
    values_from = n
  ) |>
  janitor::clean_names()   |>
  ungroup() |>
  mutate_all(~replace_na(., 0)) |>
  mutate(unsolved = closed_without_arrest + open_no_arrest,
         sum = closed_without_arrest + open_no_arrest + closed_by_arrest) 

```

```{r}
prop_bal = 
  prop.test(
  x = homicide_city$unsolved[homicide_city$city_state == "Baltimore,MD" ],
  n = homicide_city$sum[homicide_city$city_state == "Baltimore,MD" ]
  ) |>
  broom::tidy() 

prop_bal |>
  knitr::kable()
```

So the estimate proportion of homicides that are unsolved in the city of Baltimore, MD is `r prop_bal$estimate`, and the confidence interval is [`r prop_bal$conf.low`, `r prop_bal$conf.high`].

```{r}
prop_test = function (city_name) {
    prop.test(
  x = homicide_city$unsolved[homicide_city$city_state == city_name],
  n = homicide_city$sum[homicide_city$city_state == city_name]
  ) |>
    broom::tidy()
}

city = data.frame(city = pull(homicide_city, city_state)) 
prob_test_res = purrr::map_df(pull(homicide_city, city_state), prop_test)
prob_city = bind_cols(city, prob_test_res) 
ggplot(prob_city, aes(x = city, y = estimate)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0.2, color = "blue") +
  theme(axis.text.x = element_text(angle = 90, hjust = 0.5, vjust = 0.5))

```
